"""empty message

Revision ID: 0b35af9d505b
Revises: 173540d39907
Create Date: 2020-02-12 21:21:08.444091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b35af9d505b'
down_revision = '173540d39907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participante', sa.Column('requerimiento_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'participante', type_='foreignkey')
    op.drop_constraint(None, 'participante', type_='foreignkey')
    op.create_foreign_key(None, 'participante', 'requerimiento', ['requerimiento_id'], ['id'])
    op.drop_column('participante', 'item_id')
    op.drop_column('participante', 'evento_id')
    op.add_column('requerimiento', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('requerimiento', 'evento_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('requerimiento', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requerimiento', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('requerimiento', 'evento_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('requerimiento', 'id')
    op.add_column('participante', sa.Column('evento_id', sa.INTEGER(), nullable=False))
    op.add_column('participante', sa.Column('item_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'participante', type_='foreignkey')
    op.create_foreign_key(None, 'participante', 'evento', ['evento_id'], ['id'])
    op.create_foreign_key(None, 'participante', 'item', ['item_id'], ['id'])
    op.drop_column('participante', 'requerimiento_id')
    # ### end Alembic commands ###
