"""empty message

Revision ID: 425c2a4a1969
Revises: d2e60fa3c397
Create Date: 2020-02-12 20:39:26.020609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425c2a4a1969'
down_revision = 'd2e60fa3c397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('fecha_limite', sa.String(length=50), nullable=False),
    sa.Column('estado_evento', sa.String(length=50), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evento')
    # ### end Alembic commands ###
