"""empty message

Revision ID: 6a7f9f4b071c
Revises: 9ec4b0cb14d4
Create Date: 2020-02-10 12:46:59.353363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a7f9f4b071c'
down_revision = '9ec4b0cb14d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evento', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'evento', 'usuario', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evento', type_='foreignkey')
    op.drop_column('evento', 'usuario_id')
    # ### end Alembic commands ###
