"""empty message

Revision ID: d2e60fa3c397
Revises: 501a641b47cf
Create Date: 2020-02-12 20:31:00.452029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e60fa3c397'
down_revision = '501a641b47cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evento')
    op.drop_table('item')
    op.drop_table('imagen')
    op.drop_table('Participante')
    op.drop_table('requerimiento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requerimiento',
    sa.Column('evento_id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.Column('cantidad_requerida', sa.INTEGER(), nullable=False),
    sa.Column('cantidad_actual', sa.INTEGER(), nullable=False),
    sa.Column('estado_requerimiento', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('evento_id', 'item_id')
    )
    op.create_table('Participante',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.Column('evento_id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('cantidad_Aportada', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id', 'item_id', 'evento_id', 'usuario_id')
    )
    op.create_table('imagen',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('evento_id', sa.INTEGER(), nullable=True),
    sa.Column('imagen_Evento', sa.VARCHAR(length=250), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evento',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=200), nullable=False),
    sa.Column('fecha_limite', sa.VARCHAR(length=50), nullable=False),
    sa.Column('estado_evento', sa.VARCHAR(length=50), nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
