"""empty message

Revision ID: ee579ce50fe8
Revises: f31e33d2f060
Create Date: 2020-02-21 14:03:24.907350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee579ce50fe8'
down_revision = 'f31e33d2f060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'apellido',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('usuario', 'nombre',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('usuario', 'nombre_usuario',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'nombre_usuario',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('usuario', 'nombre',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('usuario', 'apellido',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
